server {
    listen 80;
    server_name localhost;
    root /usr/share/nginx/html;
    index index.html;

    location / {
        # Gère les routes Angular (ex: /connexion)
        try_files $uri $uri/ /index.html;
    }

    # Optimisation pour les images (public/)
    location ~* \.(?:ico|css|js|gif|jpe?g|png|svg|woff2?|eot|ttf|otf)$ {
        expires 6M;
        access_log off;
        add_header Cache-Control "public";
    }
}